kind = "api"
previewPath = "/"
title = "PerspeakAI"

[[services]]
localPort = 8001
name = "PerspeakAI"
paths = ["/"]

[services.development]
run = "python app.py"

[services.development.env]
PORT = "8001"

[services.production]

[services.production.run]
args = ["python", "app.py"]

[services.production.run.env]
PORT = "8001"
FLASK_ENV = "production"

[services.production.health.startup]
path = "/"
