kind = "api"
previewPath = "/"
title = "PerspeakAI"

[[services]]
localPort = 8001
name = "PerspeakAI"
paths = ["/"]

[services.development]
run = "python app.py"

[services.development.env]
PORT = "8001"

[services.production]
run = "gunicorn -w 2 -b 0.0.0.0:$PORT app:app"

[services.production.env]
PORT = "8001"
FLASK_ENV = "production"

[services.production.health.startup]
path = "/"
